name: Platform Validation

on:
  pull_request:
    types:
    - opened
    - reopened
    - synchronize
    - ready_for_review
  push:
    branches:
      - '!main'
    
jobs:
  dbt_ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.6'

      - name: Install Requirements
        run: pip install -r requirements.txt 

      - name: Install dbt Dependencies
        run: dbt deps

      - name: Full dbt Run
        run: dbt run

