name: Platform Validation

on:
  pull_request:
    types:
    - opened
    - reopened
    - synchronize
    - ready_for_review
  push:
    branches:
      - '!main'
    
jobs:
  build-macos:
      name: Validate Getting Started works on macOS
      runs-on: macos-latest
      steps:
        - uses: actions/checkout@v3
        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: "3.8.x"
        - name: Full Deploy Commands
          run: |
            dbt build
            dbt docs generate
            duckcli dev.duckdb -e "select * from rick_and_morty_characters"
          shell: bash

